import pandas as pd
from pathlib import Path

# Import LLM insights generator
from .llm_insights import build_intelligent_report

# -------------------------------
# Configuration
# -------------------------------
DATA_DIR = Path(__file__).resolve().parents[2] / "data"
RATED_POWER_KW = 2000
INTERVAL_MIN = 10  # SCADA interval in minutes


# ==========================================================
# 1. LOAD ALL INPUT FILES
# ==========================================================
def load_inputs():
    """Loads all relevant SCADA + analytics files."""

    scada = pd.read_parquet(DATA_DIR / "wind_scada_clean.parquet")

    # Optional files (not all steps must run)
    def safe_read_csv(filename):
        try:
            path = DATA_DIR / filename
            df = pd.read_csv(path, parse_dates=["timestamp"], low_memory=False)
            print(f"Loaded {filename}: {df.shape}")
            return df
        except Exception:
            print(f"Warning: {filename} not found.")
            return None

    fault_diag = safe_read_csv("fault_diagnosis_results.csv")
    trouble = safe_read_csv("troubleshooting_recommendations.csv")
    health = None

    # Health scores have no timestamp; read normally
    try:
        health = pd.read_csv(DATA_DIR / "turbine_health_scores.csv")
        print(f"Loaded turbine_health_scores.csv: {health.shape}")
    except Exception:
        print("Warning: turbine_health_scores.csv not found.")

    return scada, fault_diag, trouble, health


# ==========================================================
# 2. FARM KPI CALCULATIONS
# ==========================================================
def compute_farm_kpis(df: pd.DataFrame):
    """Calculate total energy, CF, availability for entire wind farm."""

    df = df.copy()
    df["energy_kwh"] = df["power_kw"] * (INTERVAL_MIN / 60)

    n_turbines = df["turbine_id"].nunique()
    total_energy = df["energy_kwh"].sum()

    time_span_hours = (df["timestamp"].max() - df["timestamp"].min()).total_seconds() / 3600
    installed_kw = n_turbines * RATED_POWER_KW

    capacity_factor = total_energy / (installed_kw * time_span_hours)
    availability = 1 - (df["status_code"] == 2).mean()

    return {
        "n_turbines": n_turbines,
        "total_energy_kwh": total_energy,
        "capacity_factor": capacity_factor,
        "availability": availability,
        "hours": time_span_hours,
    }


# ==========================================================
# 3. PER-TURBINE KPI CALCULATIONS
# ==========================================================
def compute_per_turbine_kpis(df: pd.DataFrame):
    """Compute energy + CF + availability for each turbine."""

    df = df.copy()
    df["energy_kwh"] = df["power_kw"] * (INTERVAL_MIN / 60)
    hours = (df["timestamp"].max() - df["timestamp"].min()).total_seconds() / 3600

    grouped = (
        df.groupby("turbine_id")
          .agg(
              energy_kwh=("energy_kwh", "sum"),
              fault_fraction=("status_code", lambda s: (s == 2).mean()),
          )
          .reset_index()
    )

    grouped["capacity_factor"] = grouped["energy_kwh"] / (RATED_POWER_KW * hours)
    grouped["availability"] = 1 - grouped["fault_fraction"]

    return grouped.sort_values("capacity_factor", ascending=False)


# ==========================================================
# 4. SUMMARIZE FAULT DIAGNOSIS
# ==========================================================
def summarize_faults(fault_diag):
    """Summarize counts per diagnosis type."""
    if fault_diag is None:
        return None

    counts = fault_diag["diagnosis"].value_counts().reset_index()
    counts.columns = ["diagnosis", "count"]
    return counts


# ==========================================================
# 5. SUMMARIZE PREDICTIVE HEALTH SCORES
# ==========================================================
def summarize_health(health):
    if health is None:
        return None
    return health.sort_values("health_score")


# ==========================================================
# 6. CREATE FINAL MARKDOWN REPORT
# ==========================================================
def build_report_text(farm_kpis, per_t_kpis, fault_counts=None, health=None):
    """Builds a markdown text report."""

    lines = []
    lines.append("# 🌬️ Wind Farm Health Report")
    lines.append("")
    lines.append("Generated by Hybrid AI Operator System")
    lines.append("")

    # -------------------------
    # Section 1: Farm Summary
    # -------------------------
    lines.append("## 1. Farm Summary")
    lines.append(f"- Number of turbines: **{farm_kpis['n_turbines']}**")
    lines.append(f"- Total Energy: **{farm_kpis['total_energy_kwh']:.2f} kWh**")
    lines.append(f"- Capacity Factor: **{farm_kpis['capacity_factor']*100:.2f}%**")
    lines.append(f"- Availability: **{farm_kpis['availability']*100:.2f}%**")
    lines.append("")

    # -------------------------
    # Section 2: Per Turbine KPIs
    # -------------------------
    lines.append("## 2. Per-Turbine Performance Ranking")
    lines.append("")
    for _, row in per_t_kpis.iterrows():
        lines.append(
            f"- **{row['turbine_id']}** → "
            f"Energy: {row['energy_kwh']:.1f} kWh | "
            f"CF: {row['capacity_factor']*100:.2f}% | "
            f"Availability: {row['availability']*100:.2f}%"
        )
    lines.append("")

    # -------------------------
    # Section 3: Fault Summary
    # -------------------------
    if fault_counts is not None:
        lines.append("## 3. Fault Diagnosis Summary")
        lines.append("")
        for _, row in fault_counts.iterrows():
            lines.append(f"- **{row['diagnosis']}**: {row['count']} events")
        lines.append("")

    # -------------------------
    # Section 4: Predictive Health Summary
    # -------------------------
    if health is not None:
        lines.append("## 4. Predictive Maintenance – Health Scores")
        lines.append("")
        for _, row in health.iterrows():
            lines.append(
                f"- **{row['turbine_id']}** → "
                f"Health Score: {row['health_score']:.1f} | "
                f"Oil Temp: {row.get('oil_temp', float('nan')):.1f}°C | "
                f"Vibration: {row.get('vibration', float('nan')):.2f} g | "
                f"Yaw: {row.get('yaw', float('nan')):.1f}°"
            )
        lines.append("")

    lines.append("## 5. Notes")
    lines.append("- This report is automatically generated using SCADA analytics, fault diagnosis, and predictive maintenance.")
    lines.append("- Use this as daily or weekly operational insight.")
    lines.append("")

    return "\n".join(lines)


# ==========================================================
# 7. SAVE REPORT (MD + PDF)
# ==========================================================
def save_report(text, filename="wind_farm_health_report.md", generate_pdf=True):
    """
    Save report as Markdown and optionally as PDF.
    
    Args:
        text: Report content in Markdown format
        filename: Output filename for markdown
        generate_pdf: If True, also generate PDF version
    """
    # Save Markdown
    md_path = DATA_DIR / filename
    with open(md_path, "w") as f:
        f.write(text)
    print(f"Report saved (MD): {md_path}")
    
    # Generate PDF if requested
    if generate_pdf:
        try:
            import markdown
            from weasyprint import HTML, CSS
            
            # Convert Markdown to HTML
            html_content = markdown.markdown(
                text, 
                extensions=['tables', 'fenced_code', 'nl2br']
            )
            
            # Professional CSS styling for PDF
            css_style = """
            @page {
                size: A4;
                margin: 2cm;
            }
            body {
                font-family: 'Helvetica Neue', Arial, sans-serif;
                font-size: 11pt;
                line-height: 1.6;
                color: #333;
            }
            h1 {
                color: #1a5f7a;
                border-bottom: 3px solid #1a5f7a;
                padding-bottom: 10px;
                font-size: 24pt;
            }
            h2 {
                color: #2c7da0;
                border-bottom: 1px solid #ddd;
                padding-bottom: 5px;
                margin-top: 25px;
                font-size: 16pt;
            }
            h3 {
                color: #468faf;
                font-size: 13pt;
            }
            h4 {
                color: #61a5c2;
                font-size: 12pt;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
            }
            th, td {
                border: 1px solid #ddd;
                padding: 10px;
                text-align: left;
            }
            th {
                background-color: #1a5f7a;
                color: white;
            }
            tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            ul, ol {
                margin-left: 20px;
            }
            li {
                margin-bottom: 5px;
            }
            strong {
                color: #1a5f7a;
            }
            hr {
                border: none;
                border-top: 2px solid #e0e0e0;
                margin: 20px 0;
            }
            em {
                color: #666;
                font-style: italic;
            }
            code {
                background-color: #f4f4f4;
                padding: 2px 5px;
                border-radius: 3px;
                font-family: monospace;
            }
            .executive-summary {
                background-color: #f0f7fa;
                padding: 15px;
                border-left: 4px solid #1a5f7a;
                margin: 15px 0;
            }
            """
            
            # Wrap HTML with proper structure
            full_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>Wind Farm Health Report</title>
            </head>
            <body>
                {html_content}
            </body>
            </html>
            """
            
            # Generate PDF
            pdf_filename = filename.replace('.md', '.pdf')
            pdf_path = DATA_DIR / pdf_filename
            
            HTML(string=full_html).write_pdf(
                pdf_path,
                stylesheets=[CSS(string=css_style)]
            )
            print(f"Report saved (PDF): {pdf_path}")
            
        except ImportError as e:
            print(f"Warning: PDF generation skipped. Install dependencies: pip install markdown weasyprint")
            print(f"Error: {e}")
        except Exception as e:
            print(f"Warning: PDF generation failed: {e}")


# ==========================================================
# 8. MAIN ENTRY
# ==========================================================
def main(use_llm_insights: bool = True):
    """
    Generate wind farm health report.
    
    Args:
        use_llm_insights: If True, generate LLM-enhanced intelligent report.
                         If False, use basic template-based report.
    """
    scada, fault_diag, trouble, health = load_inputs()

    farm_kpis = compute_farm_kpis(scada)
    per_turbine_kpis = compute_per_turbine_kpis(scada)
    fault_summary = summarize_faults(fault_diag)
    health_summary = summarize_health(health)
    
    # Count underperformance events
    try:
        underperf = pd.read_csv(DATA_DIR / "underperformance_events.csv")
        underperf_count = len(underperf)
    except:
        underperf_count = 0

    if use_llm_insights and health is not None:
        # Generate intelligent LLM-enhanced report
        print("\n Generating LLM-Enhanced Intelligent Report...")
        
        # Convert fault summary to dict
        fault_dict = dict(zip(fault_summary["diagnosis"], fault_summary["count"])) if fault_summary is not None else {}
        
        report_text = build_intelligent_report(
            farm_kpis=farm_kpis,
            per_turbine_kpis=per_turbine_kpis,
            fault_summary=fault_dict,
            health_data=health,
            underperf_count=underperf_count
        )
        save_report(report_text, filename="wind_farm_intelligent_report.md")
        # save_report(report_text, filename="wind_farm_intelligent_report.pdf")
    else:
        # Use basic template-based report
        print("\n Generating Basic Template Report...")
        report_text = build_report_text(
            farm_kpis=farm_kpis,
            per_t_kpis=per_turbine_kpis,
            fault_counts=fault_summary,
            health=health_summary
        )
        save_report(report_text, filename="wind_farm_health_report.md")

if __name__ == "__main__":
    main(use_llm_insights=True)
